
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: your_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - etl_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - etl_network

volumes:
  postgres_data:

networks:
  etl_network:
